import { describe, expect, it } from "vitest";

import { buildStrategyLabInitialData } from "../strategyLabInitialData";

describe("buildStrategyLabInitialData", () => {
  it("只预选持仓或开启观察的资产，并保留服务端最小下单额", () => {
    const data = buildStrategyLabInitialData({
      assets: [
        {
          assetKey: "US::AAPL",
          symbol: "AAPL",
          name: "Apple",
          displayNameZh: "苹果",
          market: "US",
          currency: "USD",
          assetClass: "EQUITY",
          region: "US",
          exchange: "NASDAQ",
          instrumentType: "stock",
          marketGroup: "US",
          yfinanceSymbol: "AAPL",
          holdingQty: 10,
          holdingPrice: 100,
          costBasis: null,
          costBasisInBase: null,
          unrealizedPnlBase: null,
          unrealizedPnlPct: null,
          holdingTags: [],
          watchEnabled: false,
          targetWeightHint: 0,
          watchTags: [],
          notes: null,
          priceAlertAbove: null,
          priceAlertBelow: null,
          lastPrice: 100,
          priceUpdatedAt: null,
          priceStatus: "fresh",
          priceSource: "test",
          priceAgeSec: null,
          valuationBase: null,
          fxRateToBase: null,
          fxMissing: false,
          actualWeightPct: 0,
          targetWeightPct: 0,
          gapPct: null,
          hfSignal: null,
        },
        {
          assetKey: "US::QQQ",
          symbol: "QQQ",
          name: "QQQ",
          displayNameZh: "纳指ETF",
          market: "US",
          currency: "USD",
          assetClass: "ETF",
          region: "US",
          exchange: "NASDAQ",
          instrumentType: "etf",
          marketGroup: "US",
          yfinanceSymbol: "QQQ",
          holdingQty: 0,
          holdingPrice: 0,
          costBasis: null,
          costBasisInBase: null,
          unrealizedPnlBase: null,
          unrealizedPnlPct: null,
          holdingTags: [],
          watchEnabled: true,
          targetWeightHint: 0,
          watchTags: [],
          notes: null,
          priceAlertAbove: null,
          priceAlertBelow: null,
          lastPrice: 0,
          priceUpdatedAt: null,
          priceStatus: "fresh",
          priceSource: "test",
          priceAgeSec: null,
          valuationBase: null,
          fxRateToBase: null,
          fxMissing: false,
          actualWeightPct: 0,
          targetWeightPct: 0,
          gapPct: null,
          hfSignal: null,
        },
        {
          assetKey: "US::TLT",
          symbol: "TLT",
          name: "TLT",
          displayNameZh: "长债ETF",
          market: "US",
          currency: "USD",
          assetClass: "BOND",
          region: "US",
          exchange: "NASDAQ",
          instrumentType: "etf",
          marketGroup: "US",
          yfinanceSymbol: "TLT",
          holdingQty: 0,
          holdingPrice: 0,
          costBasis: null,
          costBasisInBase: null,
          unrealizedPnlBase: null,
          unrealizedPnlPct: null,
          holdingTags: [],
          watchEnabled: false,
          targetWeightHint: 0,
          watchTags: [],
          notes: null,
          priceAlertAbove: null,
          priceAlertBelow: null,
          lastPrice: 0,
          priceUpdatedAt: null,
          priceStatus: "fresh",
          priceSource: "test",
          priceAgeSec: null,
          valuationBase: null,
          fxRateToBase: null,
          fxMissing: false,
          actualWeightPct: 0,
          targetWeightPct: 0,
          gapPct: null,
          hfSignal: null,
        },
        {
          assetKey: "HK::9988.HK",
          symbol: "9988.HK",
          name: "Alibaba",
          displayNameZh: "阿里巴巴",
          market: "HK",
          currency: "HKD",
          assetClass: "EQUITY",
          region: "HK",
          exchange: "HKEX",
          instrumentType: "stock",
          marketGroup: "HK",
          yfinanceSymbol: "9988.HK",
          holdingQty: 0.00000066,
          holdingPrice: 127.6,
          costBasis: null,
          costBasisInBase: null,
          unrealizedPnlBase: null,
          unrealizedPnlPct: null,
          holdingTags: [],
          watchEnabled: false,
          targetWeightHint: 0,
          watchTags: [],
          notes: null,
          priceAlertAbove: null,
          priceAlertBelow: null,
          lastPrice: 104.9,
          priceUpdatedAt: null,
          priceStatus: "fresh",
          priceSource: "test",
          priceAgeSec: null,
          valuationBase: 0.00001,
          fxRateToBase: 0.128,
          fxMissing: false,
          actualWeightPct: 0.0000001,
          targetWeightPct: 0,
          gapPct: null,
          hfSignal: null,
        },
      ],
      baseCurrency: "USD",
      minOrderNotional: 200,
    });

    expect(data.selectedAssets).toEqual(["US::AAPL", "US::QQQ"]);
    expect(data.minOrderNotional).toBe(200);
    expect(data.baseCurrency).toBe("USD");
  });
});
