export type TradeTicketSource = "manual" | "decision";
export type TradeTicketStatus = "ready" | "submitted" | "partially_filled" | "executed" | "canceled" | "rejected";
export type TradeTicketSide = "BUY" | "SELL";

export type TradeTicket = {
  ticketId: string;
  basketId: string;
  assetKey: string;
  cycleId: string | null;
  source: TradeTicketSource;
  status: TradeTicketStatus;
  symbol: string;
  market: string;
  instrumentCurrency: string;
  baseCurrency: string;
  side: TradeTicketSide;
  qty: number;
  price: number;
  fee: number;
  grossNotional: number;
  fxRateToBase: number | null;
  notionalInBase: number;
  decisionRefId: string | null;
  reasonTags: string[];
  reasonText: string | null;
  snapshotBefore: Record<string, unknown>;
  snapshotAfter: Record<string, unknown> | null;
  rejectCode: string | null;
  rejectMessage: string | null;
  pricingMode: "manual" | "market";
  priceSource: string | null;
  priceSnapshotAt: string | null;
  brokerKind: "sim" | "crypto_paper" | null;
  brokerAccountId: string | null;
  brokerOrderId: string | null;
  brokerStatus: string | null;
  filledQty: number | null;
  avgFillPrice: number | null;
  lastBrokerSyncAt: string | null;
  lastAppliedFillQty: number;
  brokerRejectReason: string | null;
  brokerRaw: Record<string, unknown> | null;
  createdBy: string;
  createdAt: string;
  executedAt: string | null;
  canceledAt: string | null;
  updatedAt: string;
};
