import type { DaaActorHoldingSnapshot, DaaHumanActor } from "@/src/daa/hf/humanSignals";

export const HUMAN_FACTOR_DEFAULT_MARKET_SCOPES = ["US", "HK", "CN"] as const;

export const HUMAN_FACTOR_SEED_ACTORS: DaaHumanActor[] = [
  {
    actorId: "us_growth_board",
    displayName: "US Growth Board",
    kind: "institution",
    markets: ["US"],
    styleCluster: "growth",
    stance: "offensive",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 82,
      riskControlPct: 74,
      disciplinePct: 78,
      transparencyPct: 88,
      maxDrawdownPenaltyPct: 18,
    },
  },
  {
    actorId: "us_macro_balance",
    displayName: "US Macro Balance Fund",
    kind: "fund",
    markets: ["US"],
    styleCluster: "macro",
    stance: "defensive",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 76,
      riskControlPct: 89,
      disciplinePct: 81,
      transparencyPct: 90,
      maxDrawdownPenaltyPct: 12,
    },
  },
  {
    actorId: "hk_tech_alpha",
    displayName: "HK Tech Alpha",
    kind: "fund_manager",
    markets: ["HK"],
    styleCluster: "trend",
    stance: "offensive",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 74,
      riskControlPct: 70,
      disciplinePct: 72,
      transparencyPct: 79,
      maxDrawdownPenaltyPct: 22,
    },
  },
  {
    actorId: "hk_income_guard",
    displayName: "HK Income Guard",
    kind: "fund",
    markets: ["HK"],
    styleCluster: "income",
    stance: "defensive",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 71,
      riskControlPct: 85,
      disciplinePct: 82,
      transparencyPct: 84,
      maxDrawdownPenaltyPct: 14,
    },
  },
  {
    actorId: "cn_core_equity",
    displayName: "CN Core Equity",
    kind: "institution",
    markets: ["CN"],
    styleCluster: "value",
    stance: "neutral",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 79,
      riskControlPct: 77,
      disciplinePct: 80,
      transparencyPct: 76,
      maxDrawdownPenaltyPct: 16,
    },
  },
  {
    actorId: "cn_dividend_shield",
    displayName: "CN Dividend Shield",
    kind: "fund",
    markets: ["CN"],
    styleCluster: "dividend",
    stance: "defensive",
    sourcePolicy: "official_first",
    quality: {
      accuracyPct: 69,
      riskControlPct: 87,
      disciplinePct: 84,
      transparencyPct: 81,
      maxDrawdownPenaltyPct: 11,
    },
  },
];

export const HUMAN_FACTOR_SEED_HOLDINGS: DaaActorHoldingSnapshot[] = [
  {
    snapshotId: "usg-2026q1-spy",
    actorId: "us_growth_board",
    symbol: "SPY",
    market: "US",
    asOfDate: "2026-02-20",
    disclosedAt: "2026-02-26T12:00:00.000Z",
    weightPct: 11.2,
    prevWeightPct: 9.4,
    shares: 160000,
    marketValueUsd: 87000000,
    sourceChannel: "official_regulatory",
    sourceName: "SEC 13F",
    sourceRef: "https://www.sec.gov/",
    confidencePct: 96,
  },
  {
    snapshotId: "usg-2026q1-qqq",
    actorId: "us_growth_board",
    symbol: "QQQ",
    market: "US",
    asOfDate: "2026-02-20",
    disclosedAt: "2026-02-26T12:00:00.000Z",
    weightPct: 8.9,
    prevWeightPct: 10.5,
    shares: 98000,
    marketValueUsd: 48000000,
    sourceChannel: "official_regulatory",
    sourceName: "SEC 13F",
    sourceRef: "https://www.sec.gov/",
    confidencePct: 96,
  },
  {
    snapshotId: "umb-2026m2-bnd",
    actorId: "us_macro_balance",
    symbol: "BND",
    market: "US",
    asOfDate: "2026-02-25",
    disclosedAt: "2026-02-27T08:00:00.000Z",
    weightPct: 13.5,
    prevWeightPct: 11.8,
    shares: 510000,
    marketValueUsd: 37500000,
    sourceChannel: "official_fund_house",
    sourceName: "Fund Monthly Factsheet",
    sourceRef: "https://example.com/us-macro-balance/factsheet",
    confidencePct: 88,
  },
  {
    snapshotId: "umb-2026m2-tlt",
    actorId: "us_macro_balance",
    symbol: "TLT",
    market: "US",
    asOfDate: "2026-02-25",
    disclosedAt: "2026-02-27T08:00:00.000Z",
    weightPct: 9.7,
    prevWeightPct: 8.2,
    shares: 220000,
    marketValueUsd: 20800000,
    sourceChannel: "official_fund_house",
    sourceName: "Fund Monthly Factsheet",
    sourceRef: "https://example.com/us-macro-balance/factsheet",
    confidencePct: 88,
  },
  {
    snapshotId: "hka-2026m2-0700",
    actorId: "hk_tech_alpha",
    symbol: "0700.HK",
    market: "HK",
    asOfDate: "2026-02-18",
    disclosedAt: "2026-02-24T10:00:00.000Z",
    weightPct: 12.4,
    prevWeightPct: 8.1,
    shares: 650000,
    marketValueUsd: 32800000,
    sourceChannel: "exchange_disclosure",
    sourceName: "HKEX Disclosure",
    sourceRef: "https://www.hkex.com.hk/",
    confidencePct: 86,
  },
  {
    snapshotId: "hka-2026m2-9988",
    actorId: "hk_tech_alpha",
    symbol: "9988.HK",
    market: "HK",
    asOfDate: "2026-02-18",
    disclosedAt: "2026-02-24T10:00:00.000Z",
    weightPct: 10.1,
    prevWeightPct: 9.8,
    shares: 820000,
    marketValueUsd: 19600000,
    sourceChannel: "exchange_disclosure",
    sourceName: "HKEX Disclosure",
    sourceRef: "https://www.hkex.com.hk/",
    confidencePct: 86,
  },
  {
    snapshotId: "hig-2026m2-0005",
    actorId: "hk_income_guard",
    symbol: "0005.HK",
    market: "HK",
    asOfDate: "2026-02-16",
    disclosedAt: "2026-02-23T09:30:00.000Z",
    weightPct: 9.2,
    prevWeightPct: 9.7,
    shares: 1450000,
    marketValueUsd: 15200000,
    sourceChannel: "official_fund_house",
    sourceName: "Manager Position Report",
    sourceRef: "https://example.com/hk-income-guard/report",
    confidencePct: 83,
  },
  {
    snapshotId: "hig-2026m2-0388",
    actorId: "hk_income_guard",
    symbol: "0388.HK",
    market: "HK",
    asOfDate: "2026-02-16",
    disclosedAt: "2026-02-23T09:30:00.000Z",
    weightPct: 6.6,
    prevWeightPct: 7.5,
    shares: 380000,
    marketValueUsd: 14900000,
    sourceChannel: "official_fund_house",
    sourceName: "Manager Position Report",
    sourceRef: "https://example.com/hk-income-guard/report",
    confidencePct: 83,
  },
  {
    snapshotId: "cce-2026q1-600519",
    actorId: "cn_core_equity",
    symbol: "600519.SS",
    market: "CN",
    asOfDate: "2026-02-22",
    disclosedAt: "2026-02-27T14:00:00.000Z",
    weightPct: 7.8,
    prevWeightPct: 8.4,
    shares: 210000,
    marketValueUsd: 50500000,
    sourceChannel: "official_regulatory",
    sourceName: "CN Fund Disclosure",
    sourceRef: "https://www.amac.org.cn/",
    confidencePct: 91,
  },
  {
    snapshotId: "cce-2026q1-000858",
    actorId: "cn_core_equity",
    symbol: "000858.SZ",
    market: "CN",
    asOfDate: "2026-02-22",
    disclosedAt: "2026-02-27T14:00:00.000Z",
    weightPct: 5.9,
    prevWeightPct: 6.1,
    shares: 970000,
    marketValueUsd: 16800000,
    sourceChannel: "official_regulatory",
    sourceName: "CN Fund Disclosure",
    sourceRef: "https://www.amac.org.cn/",
    confidencePct: 91,
  },
  {
    snapshotId: "cds-2026m2-511010",
    actorId: "cn_dividend_shield",
    symbol: "511010.SS",
    market: "CN",
    asOfDate: "2026-02-24",
    disclosedAt: "2026-02-28T11:30:00.000Z",
    weightPct: 12.6,
    prevWeightPct: 11.2,
    shares: 3200000,
    marketValueUsd: 44300000,
    sourceChannel: "official_fund_house",
    sourceName: "Fund Daily Holding",
    sourceRef: "https://example.com/cn-dividend-shield/disclosure",
    confidencePct: 80,
  },
  {
    snapshotId: "cds-2026m2-600036",
    actorId: "cn_dividend_shield",
    symbol: "600036.SS",
    market: "CN",
    asOfDate: "2026-02-24",
    disclosedAt: "2026-02-28T11:30:00.000Z",
    weightPct: 4.8,
    prevWeightPct: 5.4,
    shares: 840000,
    marketValueUsd: 4810000,
    sourceChannel: "official_fund_house",
    sourceName: "Fund Daily Holding",
    sourceRef: "https://example.com/cn-dividend-shield/disclosure",
    confidencePct: 80,
  },
];
